#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 26 09:45:59 2017

@author: viper
"""

import os
import matplotlib
matplotlib.use('pgf')
import numpy as np
import matplotlib.pyplot as plt
from skimage import io
from skimage import morphology
from skimage import color
from skimage import segmentation
from skimage import feature
from skimage import filters
import main
from  sklearn import cluster
from skimage.util import img_as_float
import regiongrowing as rg

import PIL.Image as Image

plt.close('all') # Close all remaining figures


filename0 = 'I0_0.tiff'
im0 = io.imread(filename0) # Open the image
filename45 = 'I45_0.tiff'
im45 = io.imread(filename45) # Open the image
filename90 = 'I90_0.tiff'
im90 = io.imread(filename90) # Open the image
filename135 = 'I135_0.tiff'
im135 = io.imread(filename135) # Open the image

f = 0.6
bw=None
i0, j0=filters.gabor(im0, frequency = f, theta =0)
i45, j45=filters.gabor(im45, frequency = f, theta =np.deg2rad(45))
i90, j90=filters.gabor(im90, frequency = f, theta =np.deg2rad(90))
i135, j135=filters.gabor(im135, frequency = f, theta =np.deg2rad(135))
absolute = np.absolute
imsum = (i0 + i45 + i90 + i135)/4
jmsum = (j0 + j45 + j90 + j135)/4
absolute = np.absolute(imsum + 1j*jmsum)


n=2
plt.figure(1)

plt.imshow(im0, cmap='gray')
print('Choose '+str(n)+ ' points for segmentation in this order : Sky, water, others')
markers = plt.ginput(n) # n points to choose as markers/seeds
print('Init done')
markers=np.asarray(markers) # Convert a Python list to a Numpy array
seeds=markers
isFirstIteration = False
for i in range(len(seeds)):
    x_,y_ = seeds[i]
    seeds[i]=[y_,x_]
markers.astype(int)
seeds.astype(int)
imsum = morphology.dilation(imsum, morphology.square(1))
labels = main.watershed(im0, seeds,'image.png', heightmap=imsum)
plt.figure(3)
plt.imshow(imsum, cmap='gray')
plt.figure(2)
plt.imshow(color.label2rgb(labels, im0))
